// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "boilerplates/order/internal/model"
)

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

type MockPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClient) EXPECT() *MockPaymentClient_Expecter {
	return &MockPaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, userUUID, method
func (_m *MockPaymentClient) PayOrder(ctx context.Context, orderUUID string, userUUID string, method model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, userUUID, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, userUUID, method)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - userUUID string
//   - method model.PaymentMethod
func (_e *MockPaymentClient_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, userUUID interface{}, method interface{}) *MockPaymentClient_PayOrder_Call {
	return &MockPaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, userUUID, method)}
}

func (_c *MockPaymentClient_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, method model.PaymentMethod)) *MockPaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *MockPaymentClient_PayOrder_Call) Return(_a0 string, _a1 error) *MockPaymentClient_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentClient_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, model.PaymentMethod) (string, error)) *MockPaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
