// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "boilerplates/order/internal/model"
)

// MockInventoryClient is an autogenerated mock type for the InventoryClient type
type MockInventoryClient struct {
	mock.Mock
}

type MockInventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryClient) EXPECT() *MockInventoryClient_Expecter {
	return &MockInventoryClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *MockInventoryClient) ListParts(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockInventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *MockInventoryClient_Expecter) ListParts(ctx interface{}, filter interface{}) *MockInventoryClient_ListParts_Call {
	return &MockInventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *MockInventoryClient_ListParts_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *MockInventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *MockInventoryClient_ListParts_Call) Return(_a0 []model.Part, _a1 error) *MockInventoryClient_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryClient_ListParts_Call) RunAndReturn(run func(context.Context, model.PartsFilter) ([]model.Part, error)) *MockInventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInventoryClient creates a new instance of MockInventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryClient {
	mock := &MockInventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
