// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod
func (_m *MockPaymentService) Pay(ctx context.Context, orderUUID string, userUUID string, paymentMethod string) (string, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, orderUUID, userUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockPaymentService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - userUUID string
//   - paymentMethod string
func (_e *MockPaymentService_Expecter) Pay(ctx interface{}, orderUUID interface{}, userUUID interface{}, paymentMethod interface{}) *MockPaymentService_Pay_Call {
	return &MockPaymentService_Pay_Call{Call: _e.mock.On("Pay", ctx, orderUUID, userUUID, paymentMethod)}
}

func (_c *MockPaymentService_Pay_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, paymentMethod string)) *MockPaymentService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPaymentService_Pay_Call) Return(_a0 string, _a1 error) *MockPaymentService_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentService_Pay_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *MockPaymentService_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
