// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "boilerplates/order/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, orderUUID
func (_m *MockOrderService) Cancel(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockOrderService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *MockOrderService_Expecter) Cancel(ctx interface{}, orderUUID interface{}) *MockOrderService_Cancel_Call {
	return &MockOrderService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *MockOrderService_Cancel_Call) Run(run func(ctx context.Context, orderUUID string)) *MockOrderService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderService_Cancel_Call) Return(_a0 error) *MockOrderService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *MockOrderService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userUUID, partUUIDs
func (_m *MockOrderService) Create(ctx context.Context, userUUID string, partUUIDs []string) (model.Order, error) {
	ret := _m.Called(ctx, userUUID, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (model.Order, error)); ok {
		return rf(ctx, userUUID, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) model.Order); ok {
		r0 = rf(ctx, userUUID, partUUIDs)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, userUUID, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - partUUIDs []string
func (_e *MockOrderService_Expecter) Create(ctx interface{}, userUUID interface{}, partUUIDs interface{}) *MockOrderService_Create_Call {
	return &MockOrderService_Create_Call{Call: _e.mock.On("Create", ctx, userUUID, partUUIDs)}
}

func (_c *MockOrderService_Create_Call) Run(run func(ctx context.Context, userUUID string, partUUIDs []string)) *MockOrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockOrderService_Create_Call) Return(_a0 model.Order, _a1 error) *MockOrderService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_Create_Call) RunAndReturn(run func(context.Context, string, []string) (model.Order, error)) *MockOrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, orderUUID
func (_m *MockOrderService) Get(ctx context.Context, orderUUID string) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *MockOrderService_Expecter) Get(ctx interface{}, orderUUID interface{}) *MockOrderService_Get_Call {
	return &MockOrderService_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *MockOrderService_Get_Call) Run(run func(ctx context.Context, orderUUID string)) *MockOrderService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrderService_Get_Call) Return(_a0 model.Order, _a1 error) *MockOrderService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *MockOrderService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function with given fields: ctx, orderUUID, method
func (_m *MockOrderService) Pay(ctx context.Context, orderUUID string, method model.PaymentMethod) (string, error) {
	ret := _m.Called(ctx, orderUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) (string, error)); ok {
		return rf(ctx, orderUUID, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) string); ok {
		r0 = rf(ctx, orderUUID, method)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockOrderService_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - method model.PaymentMethod
func (_e *MockOrderService_Expecter) Pay(ctx interface{}, orderUUID interface{}, method interface{}) *MockOrderService_Pay_Call {
	return &MockOrderService_Pay_Call{Call: _e.mock.On("Pay", ctx, orderUUID, method)}
}

func (_c *MockOrderService_Pay_Call) Run(run func(ctx context.Context, orderUUID string, method model.PaymentMethod)) *MockOrderService_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PaymentMethod))
	})
	return _c
}

func (_c *MockOrderService_Pay_Call) Return(_a0 string, _a1 error) *MockOrderService_Pay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_Pay_Call) RunAndReturn(run func(context.Context, string, model.PaymentMethod) (string, error)) *MockOrderService_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
